language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  # 3.6 is tested via coverage
env:
  - TARGET=test

matrix:
  include:
    - python: 3.6
      env: TARGET=lint
    - python: 3.6
      env: TARGET=coverage
      after_success:
        - if [ $TRAVIS_UPLOAD_COVERAGE == "true" ]; then
              bash <(curl -s https://codecov.io/bash);
          fi
    #- python: 2.7
    #- env: TARGET=test

install:
  - make depends PYTHON=$TRAVIS_PYTHON_PATH

script:
  #- make $TARGET PYTHON=python$TRAVIS_PYTHON_VERSION
  - make $TARGET PYTHON=$TRAVIS_PYTHON_PATH
